# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f60e03227183b1163bb7122ecd7a27d2f1331f957c3e944b2553b80d4f2673e5bf225020322f70015e4ae82b2e56483b0616c8d663e8f25addb5a47bbe06ffa

test:
  secret_key_base: ad3664877601966890031c59c3dd6106ef4c32c998f490d2f9a1ab050533cdd35fc531c88ee2089e8e1b012ec7b78341405b7ab3ea51862bd943f1010a1eab13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
